/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import contentManager from "@strapi/content-manager/strapi-admin";
import contentReleases from "@strapi/content-releases/strapi-admin";
import contentTypeBuilder from "@strapi/content-type-builder/strapi-admin";
import email from "@strapi/email/strapi-admin";
import i18N from "@strapi/i18n/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import reviewWorkflows from "@strapi/review-workflows/strapi-admin";
import upload from "@strapi/upload/strapi-admin";
import cmcc from "../../src/plugins/cmcc/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "content-manager": contentManager,
    "content-releases": contentReleases,
    "content-type-builder": contentTypeBuilder,
    email: email,
    i18n: i18N,
    "strapi-cloud": strapiCloud,
    "users-permissions": usersPermissions,
    "review-workflows": reviewWorkflows,
    upload: upload,
    cmcc: cmcc,
  },
});
